---
name: Build Ktor MQTT Library
on:
  push:
    tags:
      - '**'
env:
  ACTIONS_RUNNER_DEBUG: true
jobs:
  build:
    strategy:
      matrix:
        include:
          - target: publishAllPublicationsToMavenCentral --no-configuration-cache
            os: macos-latest
          - target: publishAllPublicationsToMavenCentral --no-configuration-cache
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "zulu"

      - name: Setup Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      - name: Build with Gradle
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: $${{ secrets.GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
        run: |
          echo $ORG_GRADLE_PROJECT_mavenCentralUsername
          ./gradlew ${{ matrix.target }}
